BlogBundle\Entity\Post:
    type: entity
    table: null
    repositoryClass: BlogBundle\Repository\PostRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: 255
        content:
            type: text
            nullable: true
        createdAt:
            type: datetime
            column: created_at
        authorId:
            type: integer
            column: author_id
            nullable: true
    lifecycleCallbacks: {  }
